name: copernicus
description: "A flutter_maps extension package for utilising the Copernicus API to retrieve sentinel satellite imagery."
version: 1.0.1
homepage: "https://github.com/danemadsen/copernicus"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_map: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
